version: "3.1"

services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=mysql2://root:password@db/app

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
